include:
  - ./yarukoto-be/docker-compose.yml

services:
  frontend:
    build:
      context: ./yarukoto-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5277
