version: '3.8'

services:
  yarukoto-be:
    build:
      context: ./yarukoto-be
      dockerfile: Dockerfile
    ports:
      - "5277:8080"

  yarukoto-fe:
    build:
      context: ./yarukoto-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
